import Guard from '@/components/account/auth'
import './globals.css'
import type { Metadata } from 'next'
// import { middleware } from '../../middleware'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body >
        <Guard>{children}</Guard>
        </body>
    </html>
  )
}
