import './globals.css'
import type { Metadata } from 'next'
// import { middleware } from '../../middleware'
import { GlobalContextProvider } from '@/context/store'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='h-screen'>
       <GlobalContextProvider>{children}</GlobalContextProvider>
        </body>
    </html>
  )
}
